//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PerculusData : DbContext
    {
        public PerculusData()
            : base("name=PerculusData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERCULUS_EXT_ACTIVESESSIONS> PERCULUS_EXT_ACTIVESESSIONS { get; set; }
        public virtual DbSet<PERCULUS_PERMISSIONS> PERCULUS_PERMISSIONS { get; set; }
        public virtual DbSet<PERCULUS_PRINTERSERVERS> PERCULUS_PRINTERSERVERS { get; set; }
        public virtual DbSet<PERCULUS_PRINTERSERVERS_LOG> PERCULUS_PRINTERSERVERS_LOG { get; set; }
        public virtual DbSet<PERCULUSSA_HT_LOCALIZATION_COMPANY> PERCULUSSA_HT_LOCALIZATION_COMPANY { get; set; }
        public virtual DbSet<PERCULUSSA_HT_LOGINLOG> PERCULUSSA_HT_LOGINLOG { get; set; }
        public virtual DbSet<PERCULUSSA_HT_MENUDATA_COMPANY> PERCULUSSA_HT_MENUDATA_COMPANY { get; set; }
        public virtual DbSet<PERCULUSSA_HT_PASSWORDHISTORY> PERCULUSSA_HT_PASSWORDHISTORY { get; set; }
        public virtual DbSet<PERCULUSSA_HT_QUEUELOG> PERCULUSSA_HT_QUEUELOG { get; set; }
        public virtual DbSet<PERCULUSSA_HT_USERRIGHTS_COMPANY> PERCULUSSA_HT_USERRIGHTS_COMPANY { get; set; }
        public virtual DbSet<PERCULUSSA_MT_COMPANY_HOSTHEADERS> PERCULUSSA_MT_COMPANY_HOSTHEADERS { get; set; }
        public virtual DbSet<PERCULUSSA_MT_ENROLLREQUESTS> PERCULUSSA_MT_ENROLLREQUESTS { get; set; }
        public virtual DbSet<PERCULUSSA_MT_GROUPUSERS> PERCULUSSA_MT_GROUPUSERS { get; set; }
        public virtual DbSet<PERCULUSSA_MT_LAYOUTMODULES> PERCULUSSA_MT_LAYOUTMODULES { get; set; }
        public virtual DbSet<PERCULUSSA_MT_ROOMGROUPS> PERCULUSSA_MT_ROOMGROUPS { get; set; }
        public virtual DbSet<PERCULUSSA_MT_ROOMLAYOUTS> PERCULUSSA_MT_ROOMLAYOUTS { get; set; }
        public virtual DbSet<PERCULUSSA_MT_ROOMUSERS> PERCULUSSA_MT_ROOMUSERS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_COMPANIES> PERCULUSSA_ST_COMPANIES { get; set; }
        public virtual DbSet<PERCULUSSA_ST_FILES> PERCULUSSA_ST_FILES { get; set; }
        public virtual DbSet<PERCULUSSA_ST_GROUPS> PERCULUSSA_ST_GROUPS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_LAYOUTS> PERCULUSSA_ST_LAYOUTS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_LOGS> PERCULUSSA_ST_LOGS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_MESSAGEQUEUE> PERCULUSSA_ST_MESSAGEQUEUE { get; set; }
        public virtual DbSet<PERCULUSSA_ST_MODULESETTINGS> PERCULUSSA_ST_MODULESETTINGS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_POLLOPTIONS> PERCULUSSA_ST_POLLOPTIONS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_POLLRESPONSES> PERCULUSSA_ST_POLLRESPONSES { get; set; }
        public virtual DbSet<PERCULUSSA_ST_REPORTS> PERCULUSSA_ST_REPORTS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_ROOMPOLLS> PERCULUSSA_ST_ROOMPOLLS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_ROOMS> PERCULUSSA_ST_ROOMS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_ROOMSTATS> PERCULUSSA_ST_ROOMSTATS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_ROOMUSERSTATS> PERCULUSSA_ST_ROOMUSERSTATS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_USERS> PERCULUSSA_ST_USERS { get; set; }
        public virtual DbSet<PERCULUSSA_ST_LOGS_OLD> PERCULUSSA_ST_LOGS_OLD { get; set; }
    
        public virtual ObjectResult<PERCULUSSA_USP_REPORTS_ROOMSTATS_Result> PERCULUSSA_USP_REPORTS_ROOMSTATS(Nullable<int> rOOMID, Nullable<int> cOMPANYID, string rES_ADMIN, string rES_PRESENTER, string rES_USER)
        {
            var rOOMIDParameter = rOOMID.HasValue ?
                new ObjectParameter("ROOMID", rOOMID) :
                new ObjectParameter("ROOMID", typeof(int));
    
            var cOMPANYIDParameter = cOMPANYID.HasValue ?
                new ObjectParameter("COMPANYID", cOMPANYID) :
                new ObjectParameter("COMPANYID", typeof(int));
    
            var rES_ADMINParameter = rES_ADMIN != null ?
                new ObjectParameter("RES_ADMIN", rES_ADMIN) :
                new ObjectParameter("RES_ADMIN", typeof(string));
    
            var rES_PRESENTERParameter = rES_PRESENTER != null ?
                new ObjectParameter("RES_PRESENTER", rES_PRESENTER) :
                new ObjectParameter("RES_PRESENTER", typeof(string));
    
            var rES_USERParameter = rES_USER != null ?
                new ObjectParameter("RES_USER", rES_USER) :
                new ObjectParameter("RES_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERCULUSSA_USP_REPORTS_ROOMSTATS_Result>("PERCULUSSA_USP_REPORTS_ROOMSTATS", rOOMIDParameter, cOMPANYIDParameter, rES_ADMINParameter, rES_PRESENTERParameter, rES_USERParameter);
        }
    
        public virtual ObjectResult<PERCULUSSA_USP_REPORTS_PARTICIPATION_Result> PERCULUSSA_USP_REPORTS_PARTICIPATION(Nullable<int> rOOMID, Nullable<int> cOMPANYID, string rES_ADMIN, string rES_PRESENTER, string rES_USER)
        {
            var rOOMIDParameter = rOOMID.HasValue ?
                new ObjectParameter("ROOMID", rOOMID) :
                new ObjectParameter("ROOMID", typeof(int));
    
            var cOMPANYIDParameter = cOMPANYID.HasValue ?
                new ObjectParameter("COMPANYID", cOMPANYID) :
                new ObjectParameter("COMPANYID", typeof(int));
    
            var rES_ADMINParameter = rES_ADMIN != null ?
                new ObjectParameter("RES_ADMIN", rES_ADMIN) :
                new ObjectParameter("RES_ADMIN", typeof(string));
    
            var rES_PRESENTERParameter = rES_PRESENTER != null ?
                new ObjectParameter("RES_PRESENTER", rES_PRESENTER) :
                new ObjectParameter("RES_PRESENTER", typeof(string));
    
            var rES_USERParameter = rES_USER != null ?
                new ObjectParameter("RES_USER", rES_USER) :
                new ObjectParameter("RES_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERCULUSSA_USP_REPORTS_PARTICIPATION_Result>("PERCULUSSA_USP_REPORTS_PARTICIPATION", rOOMIDParameter, cOMPANYIDParameter, rES_ADMINParameter, rES_PRESENTERParameter, rES_USERParameter);
        }
    
        public virtual ObjectResult<PERCULUSSA_USP_REPORTS_ROOMUSERSTATS_Result> PERCULUSSA_USP_REPORTS_ROOMUSERSTATS(Nullable<int> rOOMID, Nullable<int> cOMPANYID, string rES_ADMIN, string rES_PRESENTER, string rES_USER)
        {
            var rOOMIDParameter = rOOMID.HasValue ?
                new ObjectParameter("ROOMID", rOOMID) :
                new ObjectParameter("ROOMID", typeof(int));
    
            var cOMPANYIDParameter = cOMPANYID.HasValue ?
                new ObjectParameter("COMPANYID", cOMPANYID) :
                new ObjectParameter("COMPANYID", typeof(int));
    
            var rES_ADMINParameter = rES_ADMIN != null ?
                new ObjectParameter("RES_ADMIN", rES_ADMIN) :
                new ObjectParameter("RES_ADMIN", typeof(string));
    
            var rES_PRESENTERParameter = rES_PRESENTER != null ?
                new ObjectParameter("RES_PRESENTER", rES_PRESENTER) :
                new ObjectParameter("RES_PRESENTER", typeof(string));
    
            var rES_USERParameter = rES_USER != null ?
                new ObjectParameter("RES_USER", rES_USER) :
                new ObjectParameter("RES_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERCULUSSA_USP_REPORTS_ROOMUSERSTATS_Result>("PERCULUSSA_USP_REPORTS_ROOMUSERSTATS", rOOMIDParameter, cOMPANYIDParameter, rES_ADMINParameter, rES_PRESENTERParameter, rES_USERParameter);
        }
    
        public virtual ObjectResult<PERCULUSSA_USP_REPORTS_USERLIST_Result> PERCULUSSA_USP_REPORTS_USERLIST(Nullable<int> rOOMID, Nullable<int> cOMPANYID, string rES_ADMIN, string rES_PRESENTER, string rES_USER)
        {
            var rOOMIDParameter = rOOMID.HasValue ?
                new ObjectParameter("ROOMID", rOOMID) :
                new ObjectParameter("ROOMID", typeof(int));
    
            var cOMPANYIDParameter = cOMPANYID.HasValue ?
                new ObjectParameter("COMPANYID", cOMPANYID) :
                new ObjectParameter("COMPANYID", typeof(int));
    
            var rES_ADMINParameter = rES_ADMIN != null ?
                new ObjectParameter("RES_ADMIN", rES_ADMIN) :
                new ObjectParameter("RES_ADMIN", typeof(string));
    
            var rES_PRESENTERParameter = rES_PRESENTER != null ?
                new ObjectParameter("RES_PRESENTER", rES_PRESENTER) :
                new ObjectParameter("RES_PRESENTER", typeof(string));
    
            var rES_USERParameter = rES_USER != null ?
                new ObjectParameter("RES_USER", rES_USER) :
                new ObjectParameter("RES_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERCULUSSA_USP_REPORTS_USERLIST_Result>("PERCULUSSA_USP_REPORTS_USERLIST", rOOMIDParameter, cOMPANYIDParameter, rES_ADMINParameter, rES_PRESENTERParameter, rES_USERParameter);
        }
    }
}
