//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_POLLOPTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERCULUSSA_ST_POLLOPTIONS()
        {
            this.PERCULUSSA_ST_POLLRESPONSES = new HashSet<PERCULUSSA_ST_POLLRESPONSES>();
        }
    
        public int OPTIONID { get; set; }
        public Nullable<int> POLLID { get; set; }
        public string LABEL { get; set; }
        public string TEXT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_POLLRESPONSES> PERCULUSSA_ST_POLLRESPONSES { get; set; }
        public virtual PERCULUSSA_ST_ROOMPOLLS PERCULUSSA_ST_ROOMPOLLS { get; set; }
    }
}
