//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_ROOMSTATS
    {
        public int STATID { get; set; }
        public int ROOMID { get; set; }
        public string SESSIONNAME { get; set; }
        public int COMPANYID { get; set; }
        public int DURATIONACTIVE { get; set; }
        public int USERCOUNT { get; set; }
        public int BANNEDCOUNT { get; set; }
        public int CAMCOUNT { get; set; }
        public int CAMUSERCOUNT { get; set; }
        public int MICCOUNT { get; set; }
        public int MICUSERCOUNT { get; set; }
        public int SCRNSHARECOUNT { get; set; }
        public int SCRNSHAREUSERCOUNT { get; set; }
        public int DOCCOUNT { get; set; }
        public int POLLCOUNT { get; set; }
    }
}
