//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_LAYOUTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERCULUSSA_ST_LAYOUTS()
        {
            this.PERCULUSSA_MT_LAYOUTMODULES = new HashSet<PERCULUSSA_MT_LAYOUTMODULES>();
            this.PERCULUSSA_MT_ROOMLAYOUTS = new HashSet<PERCULUSSA_MT_ROOMLAYOUTS>();
        }
    
        public int LAYOUTID { get; set; }
        public string LAYOUTNAME { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> AUTHORID { get; set; }
        public int COMPANYID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public bool ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_LAYOUTMODULES> PERCULUSSA_MT_LAYOUTMODULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_ROOMLAYOUTS> PERCULUSSA_MT_ROOMLAYOUTS { get; set; }
        public virtual PERCULUSSA_ST_COMPANIES PERCULUSSA_ST_COMPANIES { get; set; }
    }
}
