//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_HT_PASSWORDHISTORY
    {
        public int LOGID { get; set; }
        public int USERID { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime LOGDATE { get; set; }
    }
}
