//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_ROOMUSERSTATS
    {
        public int STATID { get; set; }
        public int ROOMUSERID { get; set; }
        public int ROOMID { get; set; }
        public string SESSIONNAME { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FIRSTATTEMPTLIVE { get; set; }
        public Nullable<System.DateTime> LASTATTEMPTLIVE { get; set; }
        public Nullable<System.DateTime> FIRSTATTEMPTREPLAY { get; set; }
        public Nullable<System.DateTime> LASTATTEMPTREPLAY { get; set; }
        public int DURATIONLIVE { get; set; }
        public int DURATIONACTIVE { get; set; }
        public int DURATIONPASSIVE { get; set; }
        public int DURATIONREPLAY { get; set; }
        public int REPLAYCOUNT { get; set; }
        public int CAMDURATION { get; set; }
        public int MICDURATION { get; set; }
        public int DOCCOUNT { get; set; }
        public int CHATMSGCOUNT { get; set; }
        public int SCRNSHARECOUNT { get; set; }
        public int POLLCOUNT { get; set; }
        public string USERMODE { get; set; }
        public string ATTENDCODE { get; set; }
    }
}
