//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_ROOMPOLLS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERCULUSSA_ST_ROOMPOLLS()
        {
            this.PERCULUSSA_ST_POLLOPTIONS = new HashSet<PERCULUSSA_ST_POLLOPTIONS>();
        }
    
        public int POLLID { get; set; }
        public Nullable<int> ROOMID { get; set; }
        public string QUESTION { get; set; }
        public int TIMELIMIT { get; set; }
        public byte STATUS { get; set; }
        public bool PUBLICRESULTS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public byte POLLTYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_POLLOPTIONS> PERCULUSSA_ST_POLLOPTIONS { get; set; }
        public virtual PERCULUSSA_ST_ROOMS PERCULUSSA_ST_ROOMS { get; set; }
    }
}
