//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_FILES
    {
        public int FILEID { get; set; }
        public System.Guid FILEGUID { get; set; }
        public int COMPANYID { get; set; }
        public int OBJECTID { get; set; }
        public byte OBJECTTYPE { get; set; }
        public string FOLDERNAME { get; set; }
        public string FILENAME { get; set; }
        public string LABEL { get; set; }
        public Nullable<long> FILESIZE { get; set; }
        public byte FILETYPE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public int PAGE { get; set; }
    }
}
