//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_COMPANIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERCULUSSA_ST_COMPANIES()
        {
            this.PERCULUSSA_HT_LOCALIZATION_COMPANY = new HashSet<PERCULUSSA_HT_LOCALIZATION_COMPANY>();
            this.PERCULUSSA_HT_MENUDATA_COMPANY = new HashSet<PERCULUSSA_HT_MENUDATA_COMPANY>();
            this.PERCULUSSA_HT_USERRIGHTS_COMPANY = new HashSet<PERCULUSSA_HT_USERRIGHTS_COMPANY>();
            this.PERCULUSSA_MT_COMPANY_HOSTHEADERS = new HashSet<PERCULUSSA_MT_COMPANY_HOSTHEADERS>();
            this.PERCULUSSA_ST_GROUPS = new HashSet<PERCULUSSA_ST_GROUPS>();
            this.PERCULUSSA_ST_LAYOUTS = new HashSet<PERCULUSSA_ST_LAYOUTS>();
            this.PERCULUSSA_ST_ROOMS = new HashSet<PERCULUSSA_ST_ROOMS>();
        }
    
        public int COMPANYID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> COMPANY_QUOTA { get; set; }
        public Nullable<int> ROOMS_MAXALLOWED { get; set; }
        public Nullable<int> ROOMS_MAXUSERSPERROOM { get; set; }
        public Nullable<int> ROOMS_MAXACTIVE { get; set; }
        public Nullable<int> ROOMS_MAXDURATION { get; set; }
        public Nullable<int> USERS_MAXADMINS { get; set; }
        public Nullable<int> USERS_MAXLECTURERS { get; set; }
        public Nullable<int> USERS_MAXUSERS { get; set; }
        public Nullable<int> USERS_SIMULTANEOUSUSERS { get; set; }
        public Nullable<System.DateTime> EXPIRES { get; set; }
        public string CULTURE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACTPERSON { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<int> PAGESIZE { get; set; }
        public Nullable<int> USERADDED { get; set; }
        public Nullable<int> USERMODIFIED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_HT_LOCALIZATION_COMPANY> PERCULUSSA_HT_LOCALIZATION_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_HT_MENUDATA_COMPANY> PERCULUSSA_HT_MENUDATA_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_HT_USERRIGHTS_COMPANY> PERCULUSSA_HT_USERRIGHTS_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_COMPANY_HOSTHEADERS> PERCULUSSA_MT_COMPANY_HOSTHEADERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_GROUPS> PERCULUSSA_ST_GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_LAYOUTS> PERCULUSSA_ST_LAYOUTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_ROOMS> PERCULUSSA_ST_ROOMS { get; set; }
    }
}
