//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUS_PERMISSIONS
    {
        public int PERMISSIONID { get; set; }
        public string PERMISSIONTYPE { get; set; }
        public string ALLOWEDUSER { get; set; }
        public Nullable<int> COMPANYID { get; set; }
    }
}
