//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_LOGS_OLD
    {
        public int LOGID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> ROOMID { get; set; }
        public Nullable<int> ROOMUSERID { get; set; }
        public Nullable<System.DateTime> ENTERDATE { get; set; }
        public Nullable<System.DateTime> EXITDATE { get; set; }
        public string IPADDRESS { get; set; }
        public Nullable<bool> ISREPLAY { get; set; }
    }
}
