//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_ROOMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERCULUSSA_ST_ROOMS()
        {
            this.PERCULUSSA_MT_ENROLLREQUESTS = new HashSet<PERCULUSSA_MT_ENROLLREQUESTS>();
            this.PERCULUSSA_MT_ROOMGROUPS = new HashSet<PERCULUSSA_MT_ROOMGROUPS>();
            this.PERCULUSSA_MT_ROOMLAYOUTS = new HashSet<PERCULUSSA_MT_ROOMLAYOUTS>();
            this.PERCULUSSA_MT_ROOMUSERS = new HashSet<PERCULUSSA_MT_ROOMUSERS>();
            this.PERCULUSSA_ST_LOGS = new HashSet<PERCULUSSA_ST_LOGS>();
            this.PERCULUSSA_ST_MODULESETTINGS = new HashSet<PERCULUSSA_ST_MODULESETTINGS>();
            this.PERCULUSSA_ST_ROOMPOLLS = new HashSet<PERCULUSSA_ST_ROOMPOLLS>();
        }
    
        public int ROOMID { get; set; }
        public string SESSIONNAME { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public Nullable<System.DateTime> BEGINDATE { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string LANGUAGEFILE { get; set; }
        public Nullable<int> SOUND_RATE { get; set; }
        public Nullable<int> VIDEO_QUALITY { get; set; }
        public Nullable<int> VIDEO_BANDWIDTH { get; set; }
        public string MEDIASERVER_IP { get; set; }
        public Nullable<int> REQUIRESLOGIN { get; set; }
        public string PASSKEY { get; set; }
        public Nullable<int> SEND_PASSKEY { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string CATEGORY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> SEND_ICS { get; set; }
        public Nullable<int> INREPLAYMODE { get; set; }
        public Nullable<long> REPLAYSIZE { get; set; }
        public string COLORCODE { get; set; }
        public int FORMENROLL_ALLOW { get; set; }
        public Nullable<int> FORMENROLL_TYPE { get; set; }
        public Nullable<int> FORMENROLL_CAPACITY { get; set; }
        public string FLASHFILE { get; set; }
        public string ROOMGUID { get; set; }
        public Nullable<int> ROOMOPTIONS { get; set; }
        public Nullable<int> STREAMCOUNT { get; set; }
        public bool STARTACTIVE { get; set; }
        public string USERRIGHTSCHEMA { get; set; }
        public string PERMITTEDSYSTEMLAYOUTS { get; set; }
        public int DEFAULTLAYOUTID { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<int> USERADDED { get; set; }
        public Nullable<int> USERMODIFIED { get; set; }
        public Nullable<bool> AUTOPACKENABLED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_ENROLLREQUESTS> PERCULUSSA_MT_ENROLLREQUESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_ROOMGROUPS> PERCULUSSA_MT_ROOMGROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_ROOMLAYOUTS> PERCULUSSA_MT_ROOMLAYOUTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_ROOMUSERS> PERCULUSSA_MT_ROOMUSERS { get; set; }
        public virtual PERCULUSSA_ST_COMPANIES PERCULUSSA_ST_COMPANIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_LOGS> PERCULUSSA_ST_LOGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_MODULESETTINGS> PERCULUSSA_ST_MODULESETTINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_ST_ROOMPOLLS> PERCULUSSA_ST_ROOMPOLLS { get; set; }
    }
}
