

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PerculusReport.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class PerculusData2 : DbContext
{
    public PerculusData2()
        : base("name=PerculusData2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<VClass> VClass { get; set; }


    public virtual ObjectResult<ActivityStats_Result> ActivityStats(Nullable<System.Guid> cOURSEID)
    {

        var cOURSEIDParameter = cOURSEID.HasValue ?
            new ObjectParameter("COURSEID", cOURSEID) :
            new ObjectParameter("COURSEID", typeof(System.Guid));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActivityStats_Result>("ActivityStats", cOURSEIDParameter);
    }


    public virtual ObjectResult<CourseStats_Result> CourseStats(Nullable<System.Guid> pROGRAMID)
    {

        var pROGRAMIDParameter = pROGRAMID.HasValue ?
            new ObjectParameter("PROGRAMID", pROGRAMID) :
            new ObjectParameter("PROGRAMID", typeof(System.Guid));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CourseStats_Result>("CourseStats", pROGRAMIDParameter);
    }


    public virtual ObjectResult<ProgramStats_Result> ProgramStats()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProgramStats_Result>("ProgramStats");
    }


    public virtual ObjectResult<CourseStats_2_Result> CourseStats_2(Nullable<System.Guid> pROGRAMID)
    {

        var pROGRAMIDParameter = pROGRAMID.HasValue ?
            new ObjectParameter("PROGRAMID", pROGRAMID) :
            new ObjectParameter("PROGRAMID", typeof(System.Guid));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CourseStats_2_Result>("CourseStats_2", pROGRAMIDParameter);
    }

}

}

