//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUS_EXT_ACTIVESESSIONS
    {
        public int ROOMUSERID { get; set; }
        public string USERIP { get; set; }
        public string SERVERIP { get; set; }
        public System.DateTime LOGDATE { get; set; }
    }
}
