//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_MESSAGEQUEUE
    {
        public int QUEUEITEMID { get; set; }
        public System.DateTime SCHEDULEDDATE { get; set; }
        public System.DateTime QUEUEDATE { get; set; }
        public Nullable<System.DateTime> PROCESSDATE { get; set; }
        public string MESSAGE { get; set; }
        public string SUBJECT { get; set; }
        public Nullable<int> ATTEMPTCOUNT { get; set; }
        public int LASTSTATUS { get; set; }
        public int OBJECTID { get; set; }
        public int OBJECTTYPE { get; set; }
        public Nullable<int> ITEMTYPE { get; set; }
        public int NOTIFYTYPE { get; set; }
        public string LASTRESULT { get; set; }
        public string ENDPOINTADDRESS { get; set; }
        public Nullable<int> COMPANYID { get; set; }
    }
}
