//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERCULUSSA_ST_GROUPS()
        {
            this.PERCULUSSA_MT_ROOMGROUPS = new HashSet<PERCULUSSA_MT_ROOMGROUPS>();
        }
    
        public int GROUPID { get; set; }
        public string GROUPNAME { get; set; }
        public int COMPANYID { get; set; }
        public int USERCOUNT { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<int> USERID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERCULUSSA_MT_ROOMGROUPS> PERCULUSSA_MT_ROOMGROUPS { get; set; }
        public virtual PERCULUSSA_ST_COMPANIES PERCULUSSA_ST_COMPANIES { get; set; }
    }
}
