//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_MT_LAYOUTMODULES
    {
        public int LAYOUTID { get; set; }
        public string MODULENAME { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public System.DateTime DATEADDED { get; set; }
    
        public virtual PERCULUSSA_ST_LAYOUTS PERCULUSSA_ST_LAYOUTS { get; set; }
    }
}
