//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUS_PRINTERSERVERS_LOG
    {
        public int LOGID { get; set; }
        public Nullable<int> PRINTERSERVERID { get; set; }
        public Nullable<int> REQUESTEDUSER { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public string ROOMNAME { get; set; }
        public string FOLDERNAME { get; set; }
        public string FILENAME { get; set; }
        public Nullable<int> FILESIZE { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public Nullable<int> ISACTIVE { get; set; }
        public System.Guid FILEGUID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> ROOMID { get; set; }
    }
}
