//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_MT_ROOMGROUPS
    {
        public int GROUPID { get; set; }
        public int ROOMID { get; set; }
        public System.DateTime DATEADDED { get; set; }
    
        public virtual PERCULUSSA_ST_GROUPS PERCULUSSA_ST_GROUPS { get; set; }
        public virtual PERCULUSSA_ST_ROOMS PERCULUSSA_ST_ROOMS { get; set; }
    }
}
