//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_POLLRESPONSES
    {
        public int OPTIONID { get; set; }
        public int ROOMUSERID { get; set; }
        public Nullable<System.DateTime> DATEVOTED { get; set; }
        public Nullable<int> VOTEDURATION { get; set; }
    
        public virtual PERCULUSSA_ST_POLLOPTIONS PERCULUSSA_ST_POLLOPTIONS { get; set; }
    }
}
