//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUS_PRINTERSERVERS
    {
        public int PRINTERSERVERID { get; set; }
        public string SERVERNAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> PAGESAHEAD { get; set; }
        public string SPOOLERDIR { get; set; }
        public Nullable<int> PRINTING_AVAILABLE { get; set; }
        public Nullable<int> SCREENSHOT_AVAILABLE { get; set; }
        public string DRIVERNAME { get; set; }
    }
}
