//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_MODULESETTINGS
    {
        public int SETTINGID { get; set; }
        public string MODULENAME { get; set; }
        public string SETTINGKEY { get; set; }
        public string SETTINGVALUE { get; set; }
        public int ROOMID { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
    
        public virtual PERCULUSSA_ST_ROOMS PERCULUSSA_ST_ROOMS { get; set; }
    }
}
