//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_MT_COMPANY_HOSTHEADERS
    {
        public int HOSTHEADERID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string HOSTHEADER { get; set; }
    
        public virtual PERCULUSSA_ST_COMPANIES PERCULUSSA_ST_COMPANIES { get; set; }
    }
}
