//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERCULUSSA_ST_REPORTS
    {
        public int REPORTID { get; set; }
        public string REPORTNAME { get; set; }
        public string SP_NAME { get; set; }
        public string PARAMETERS { get; set; }
        public string DESCRIPTION { get; set; }
        public int RANKING { get; set; }
        public bool SHOWREPORT { get; set; }
        public System.DateTime DATEADDED { get; set; }
    }
}
