//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClass
    {
        public System.Guid VClassId { get; set; }
        public int VClassKey { get; set; }
        public string Provider { get; set; }
        public int TDuration { get; set; }
        public int Duration { get; set; }
        public int Week { get; set; }
    }
}
